### ISSUE TITLE
Tableroll runs afoul of the 'checkptr' safety rules

### ISSUE THREAD

**Issue by euank** [ngrok/tableroll#22]
Specifically, if you run tableroll's tests with `-race` under go >=1.14, you'll run into a checkptr violation:

```
goroutine 21 [running]:
runtime.throw(0x9c317e, 0x3a)
	/nix/store/bqdbizzgdcckkci0splpnhgy1c13h2z0-go-1.15.3/share/go/src/runtime/panic.go:1116 +0x72 fp=0xc00007a608 sp=0xc00007a5d8 pc=0x46a692
runtime.checkptrAlignment(0xc000070072, 0x9331e0, 0x1)
	/nix/store/bqdbizzgdcckkci0splpnhgy1c13h2z0-go-1.15.3/share/go/src/runtime/checkptr.go:20 +0xc9 fp=0xc00007a638 sp=0xc00007a608 pc=0x439609
golang.org/x/sys/unix.anyToSockaddr(0x9, 0xc000070070, 0x0, 0x2e, 0x0, 0x0)
	/home/esk/go/pkg/mod/golang.org/x/sys@v0.0.0-20190124100055-b90733256f2e/unix/syscall_linux.go:814 +0x316 fp=0xc00007a750 sp=0xc00007a638 pc=0x6b98f6
golang.org/x/sys/unix.Recvmsg(0x9, 0xc00007a8d0, 0x1000, 0x1000, 0xc000018080, 0x18, 0x18, 0x0, 0x932a40, 0xc000184000, ...)
	/home/esk/go/pkg/mod/golang.org/x/sys@v0.0.0-20190124100055-b90733256f2e/unix/syscall_linux.go:1127 +0x27c fp=0xc00007a820 sp=0xc00007a750 pc=0x6bad7c
github.com/opencontainers/runc/libcontainer/utils.RecvFd(0xc0000ac048, 0x0, 0x1, 0xc000010038)
	/home/esk/go/pkg/mod/github.com/kevinburke/runc@v1.0.0-rc8.0.20190502181430-3ec7f94c7eff/libcontainer/utils/cmsg.go:49 +0x185 fp=0xc00007b970 sp=0xc00007a820 pc=0x6bd8c5
github.com/ngrok/tableroll.(*upgradeSession).getFiles(0xc0000908c0, 0xa3b960, 0xc0000a8010, 0x0, 0x0, 0x0)
	/home/esk/go/tableroll/transfer_owner.go:124 +0x78e fp=0xc00007bbc8 sp=0xc00007b970 pc=0x8eb2ce
github.com/ngrok/tableroll.(*Upgrader).becomeOwner(0xc000118000, 0xa3b960, 0xc0000a8010, 0xc0000a2ed0, 0x0, 0x0)
	/home/esk/go/tableroll/upgrader.go:124 +0x150 fp=0xc00007bc88 sp=0xc00007bbc8 pc=0x8ecfb0
github.com/ngrok/tableroll.newUpgrader(0xa3b960, 0xc0000a8010, 0xa3d040, 0xc9ca10, 0xa38440, 0xc9ca10, 0xc00001a00e, 0x1c, 0x0, 0x0, ...)
	/home/esk/go/tableroll/upgrader.go:108 +0x470 fp=0xc00007bd50 sp=0xc00007bc88 pc=0x8eccd0
github.com/ngrok/tableroll.New(...)
	/home/esk/go/tableroll/upgrader.go:82
github.com/ngrok/tableroll.main1(0x9b0a4b)
	/home/esk/go/tableroll/upgrader_process_test.go:335 +0x13a fp=0xc00007be60 sp=0xc00007bd50 pc=0x8f811a
github.com/ngrok/tableroll.TestSpawnHelper(0xc000082c00)
	/home/esk/go/tableroll/upgrader_process_test.go:319 +0x16c fp=0xc00007bed0 sp=0xc00007be60 pc=0x8f7f6c
testing.tRunner(0xc000082c00, 0x9cbc00)
	/nix/store/bqdbizzgdcckkci0splpnhgy1c13h2z0-go-1.15.3/share/go/src/testing/testing.go:1123 +0x203 fp=0xc00007bfd0 sp=0xc00007bed0 pc=0x5a38e3
runtime.goexit()
	/nix/store/bqdbizzgdcckkci0splpnhgy1c13h2z0-go-1.15.3/share/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00007bfd8 sp=0xc00007bfd0 pc=0x4a3e61
created by testing.(*T).Run
	/nix/store/bqdbizzgdcckkci0splpnhgy1c13h2z0-go-1.15.3/share/go/src/testing/testing.go:1168 +0x5bc

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000082a80, 0x9b2e06, 0xf, 0x9cbc00, 0x1)
	/nix/store/bqdbizzgdcckkci0splpnhgy1c13h2z0-go-1.15.3/share/go/src/testing/testing.go:1169 +0x5f4
testing.runTests.func1(0xc000082a80)
	/nix/store/bqdbizzgdcckkci0splpnhgy1c13h2z0-go-1.15.3/share/go/src/testing/testing.go:1439 +0xa7
testing.tRunner(0xc000082a80, 0xc0000b3ce0)
	/nix/store/bqdbizzgdcckkci0splpnhgy1c13h2z0-go-1.15.3/share/go/src/testing/testing.go:1123 +0x203
testing.runTests(0xc0000c05e0, 0xc66100, 0x14, 0x14, 0x0, 0x0, 0x0, 0x44b5a5)
	/nix/store/bqdbizzgdcckkci0splpnhgy1c13h2z0-go-1.15.3/share/go/src/testing/testing.go:1437 +0x613
testing.(*M).Run(0xc0000fc000, 0x0)
	/nix/store/bqdbizzgdcckkci0splpnhgy1c13h2z0-go-1.15.3/share/go/src/testing/testing.go:1345 +0x3b4
main.main()
	_testmain.go:81 +0x237

goroutine 22 [IO wait]:
internal/poll.runtime_pollWait(0x7fd4d063e878, 0x72, 0x72)
	/nix/store/bqdbizzgdcckkci0splpnhgy1c13h2z0-go-1.15.3/share/go/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc0000fc098, 0x72, 0x0, 0x0, 0x9b0189)
	/nix/store/bqdbizzgdcckkci0splpnhgy1c13h2z0-go-1.15.3/share/go/src/internal/poll/fd_poll_runtime.go:87 +0xe6
internal/poll.(*pollDesc).waitRead(...)
	/nix/store/bqdbizzgdcckkci0splpnhgy1c13h2z0-go-1.15.3/share/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000fc080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/nix/store/bqdbizzgdcckkci0splpnhgy1c13h2z0-go-1.15.3/share/go/src/internal/poll/fd_unix.go:394 +0x2fe
net.(*netFD).accept(0xc0000fc080, 0xc00003d6b0, 0xc00003d7c0, 0x5a38e3)
	/nix/store/bqdbizzgdcckkci0splpnhgy1c13h2z0-go-1.15.3/share/go/src/net/fd_unix.go:172 +0x58
net.(*UnixListener).accept(0xc0000a2ed0, 0x8, 0xc00003d6d0, 0x5a3808)
	/nix/store/bqdbizzgdcckkci0splpnhgy1c13h2z0-go-1.15.3/share/go/src/net/unixsock_posix.go:162 +0x50
net.(*UnixListener).AcceptUnix(0xc0000a2ed0, 0x0, 0x0, 0x0)
	/nix/store/bqdbizzgdcckkci0splpnhgy1c13h2z0-go-1.15.3/share/go/src/net/unixsock.go:247 +0x8f
github.com/ngrok/tableroll.(*Upgrader).serveUpgrades(0xc000118000)
	/home/esk/go/tableroll/upgrader.go:137 +0x57
created by github.com/ngrok/tableroll.newUpgrader
	/home/esk/go/tableroll/upgrader.go:106 +0x448

goroutine 23 [select]:
github.com/ngrok/tableroll.(*upgradeSession).getFiles.func1(0xc000096360, 0xa3b960, 0xc0000a8010, 0xc0000908c0)
	/home/esk/go/tableroll/transfer_owner.go:77 +0xfe
created by github.com/ngrok/tableroll.(*upgradeSession).getFiles
	/home/esk/go/tableroll/transfer_owner.go:76 +0x1d3
```

Obviously we should fix this violation. I'm digging into it now.

**Comment by euank** [comment]
Fixed a while ago via https://github.com/golang/sys/commit/9984515f05623565c49553bf594e265840dd3b19

We should be able to just bump x/sys/unix to fix that one.
